@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed May 21 18:12:00 -0700 2025
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
call xelab  -wto 141a23555391490ebe17d80a93b27598 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60_behav xil_defaultlib.Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
