@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed May 21 18:12:02 -0700 2025
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60_behav -key {Behavioral:sim_1:Functional:Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60} -tclbatch Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60.tcl -view C:/Users/fmabrouk/Documents/Embedded_design/IIR_Filter_3Biquads_75KHz/IIR_75BW_SingleFile/Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
