webtalk_init -webtalk_dir C:/Users/fmabrouk/Documents/Embedded_design/IIR_Filter_3Biquads_75KHz/IIR_75BW_SingleFile/IIR_75BW_SingleFile.sim/sim_1/behav/xsim/xsim.dir/Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 21 18:12:02 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211213771_1777519980_210640129_040" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e025830e-9e9c-43ec-ad1e-7126aa13e762" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "141a23555391490ebe17d80a93b27598" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "8" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "117 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "9 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.98_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "54088_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3085595116 -regid "211213771_1777519980_210640129_040" -xml C:/Users/fmabrouk/Documents/Embedded_design/IIR_Filter_3Biquads_75KHz/IIR_75BW_SingleFile/IIR_75BW_SingleFile.sim/sim_1/behav/xsim/xsim.dir/Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/fmabrouk/Documents/Embedded_design/IIR_Filter_3Biquads_75KHz/IIR_75BW_SingleFile/IIR_75BW_SingleFile.sim/sim_1/behav/xsim/xsim.dir/Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/fmabrouk/Documents/Embedded_design/IIR_Filter_3Biquads_75KHz/IIR_75BW_SingleFile/IIR_75BW_SingleFile.sim/sim_1/behav/xsim/xsim.dir/Cascaded_ChbyChevII_Fc37K5_Fp100K_Astop60_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
